[test]
root = "./test"
coverage = true

coverageSkipTestFiles = true

coveragePathIgnorePatterns = [
    "lib/defaults/**",
    "test/utils/*.ts",
    "dist/**/*.js",
    "dist/**/*.ts",
    "../**/*.ts",
    "../**/*.js"
]


[test.reporter]
junit = "junit.xml"